import Navbar from "@/component/Navbar";
import ProductProvider from "@/provider/ProductProvider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Redux Cart App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProductProvider>
          <Navbar />
          {children}
        </ProductProvider>
      </body>
    </html>
  );
}
